### ISSUE TITLE
Islandora Webform with 7.x-dev

### ISSUE THREAD

**Issue by uconnjeustis** [commonmedia/islandora_webform#21]
At the Islandora camp CT, I learned about this module and wanted to play around with it. For the camp, I installed the vm using the instructions from http://islandora-labs.github.io/islandora/install/README/ which installs the 7.x-dev version of Islandora; this is the latest release but gets this version name of dev instead of 7.x.1-5. When trying to enable Islandora webforms, it failed because it requires 7.x.1-5. Would it be possible to have this work with 7.x whether it be the dev with the vm or 7.x.1-5 and above?

**Comment by patdunlavey** [comment]
Hmm... hadn't anticipated that! The critical piece of islandora that needs to be version 7.1.5 or greater is the objective_forms module. I have no idea if the 7.x-dev vm you're using includes the updates that islandora webform needs. 
You could try disabling this requirements check in the islandora_webform.install file and see if it works. To do that, comment out 'islandora' in line 81:
 ```php
      $tests = array(
     //   'islandora' => '7.x-1.5',
        'webform' => '7.x-4.10',
      );
```

**Comment by patdunlavey** [comment]
Oh! I just noticed that the vm at the url you referred to is the 7.x-2.x version of Islandora, which is in very heavy development. Islandora Webform almost certainly will not work with that version (I have not tried it though).

I would suggest for these purposes that the 7.1.5 version of the vm is the best one to use. The download link can be found here: http://islandora.ca/downloads.

**Comment by uconnjeustis** [comment]
Thanks Pat. I hope to get a test site at work that is 7.x.1-5 where I can
get this tested. Though the link should lead to 7.x.1-5 and not 7.x.2. I'll
also try commented out those lines and see if that works.

Jennifer

**Comment by uconnjeustis** [comment]
Pat,

I commented out that line and it worked fine with the vm that I have! I'll
begin playing around with it. Thanks for writing this.
Jennifer

**Comment by psuda1** [comment]
I ran into this same problem with the Islandora Vagrant instance. I will try commenting out line 81 and report back.

**Comment by psuda1** [comment]
I commented out line 81 and it was enabled in Islandora Vagrant instance

**Comment by uconnjeustis** [comment]
I did the same thing and the problem was solved as well.

Jennifer

**Comment by patdunlavey** [comment]
I'm going to mark this as "won't fix". I can't recommend the solution that a couple comments suggested - of disabling the Islandora version check. Islandora webform ingest depends on the 7.x-1.5+ version of the objective form module.
