### ISSUE TITLE
Datastream selection wrong in IW field islandora mapping for non xml datastreams

### ISSUE THREAD

**Issue by DiegoPino** [commonmedia/islandora_webform#25]
When using a file filed, the islandora mapping option, at field edit form displays `Islandora Basic Image Content Model provides no datastreams that can be populated from this webform field type.`, even when the mime types match.

This is caused by this line https://github.com/commonmedia/islandora_webform/blob/4eee4d2824f8cdaca74ab1edbd7b0064ccdf131b/submodules/islandora_webform_ingest/includes/utilities.inc#L75
which does not allow to iterate over all mime types resulting in an empty result.

**Comment by patdunlavey** [comment]
This is fixed by pull request #26
