### ISSUE TITLE
Unable to install IW on Islandora Vagrant - HEAD modules

### ISSUE THREAD

**Issue by petermacdonald** [commonmedia/islandora_webform#29]
I'm using the Vagrant image of Islandora distributed with the 7.1.6 Islandora modules.

I upgraded all the modules to HEAD (7.x-dev), installed and enabled webform and webform_ajax, but whenI tried to enable the IW module using Drush I get this error message:

"Module islandora_webform doesn't meet the requirements to be enabled.[error]
islandora_webform requires that islandora be at least version 7.x-1.5[error](Currently using islandora 7.x-dev)"

I tried enabling it using the Drupal > Modules menu and got a similar error message:

"islandora_webform requires that islandora be at least version 7.x-1.5 (Currently using islandora 7.x-dev)"

Is there anything I can do to get IW installed while using Islandora HEAD modules?

Thanks
Peter

**Comment by patdunlavey** [comment]
Hi Peter, Can you try this patch?
[islandora_webform-issues-29-1.patch.txt](https://github.com/commonmedia/islandora_webform/files/105470/islandora_webform-issues-29-1.patch.txt)

**Comment by petermacdonald** [comment]
I had already changed "7.1.5" to "7.x-dev" in the IW code which got me in just fine. But I'd really like to apply your patch, but, alas, I don't now how to apply a patch.

Sorry to have to ask, but how do I apply/run this patch?

**Comment by patdunlavey** [comment]
1. Copy the file to path/to/islandora_webform
2. Move to that directory if you aren't there already.
3. Run the command `patch -p1 < islandora_webform-issues-29-1.patch.txt`

You might need to revert your change to get the patch to apply without errors. The only difference with what you did is that it should work for both 7.x-dev and 7.1.5+ numbered versions.

**Comment by petermacdonald** [comment]
Pat:

Running that command resulted in this message:

-jailshell: islandora_webform-issues-29-1.patch.txt: No such file or directory

Peter

**Comment by petermacdonald** [comment]
I manually moved the patched code from the patch file to the .install file and the Drupal installed it without a problem with Islandroa HEAD modules.

Peter

**Comment by petermacdonald** [comment]
[Using Islandora HEAD modules and IW cloned today 2016-02-02.]

On the Islandora site where I have configured two Webforms, all anonymous users (not an administrator) now see the following red error message at the top of Drupal's content window on all pages:

X - No fedora object PID was defined.

That message is coming from the islandora_webform_module, line 228.

I'll try to get rid of it if you have any ideas for me to try. Thanks.

See screen capture attached.

![webform-error](https://cloud.githubusercontent.com/assets/693785/12765814/62a1dd62-c9ce-11e5-859a-9644c8914a92.JPG)

**Comment by patdunlavey** [comment]
Re-opening this issue pending resolution of #30

**Comment by patdunlavey** [comment]
Pull request #31 merged.
