### ISSUE TITLE
IW MODS XML form's use of the relatedItem wrapper

### ISSUE THREAD

**Issue by petermacdonald** [commonmedia/islandora_webform#4]
I know that those of us who choose to implement the islandora_webform module are not required to use the metadata XML form that comes with the module if it doesn't meet our needs, but I've been trying to get use to the module out-of-the-box during this testing period and this means I've been using the built-in XML form all along.

But ever since I started kicking the tires on the module I've been wondering what the logic was behind the decision to have the built-in XML form use <mods:relatedItem> as the wrapper for all information concerning the submission? It would seem better and easier to configure to use top-level elements for the submission information and reserve <mods:relatedItem> to wrap information only about the "related item", that is, about the primary object.

Were there some practical reasons that lead to this decision that have escaped me?

Wrapping everything in <mods:relatedItem> seems unintuitive and even to violate the meaning of that MODS element:  "Information that identifies other resources related to the one being described." (http://www.loc.gov/standards/mods/userguide/relateditem.html)

Another problem with the XML for is that no element in this form is crosswalked to <dc:title> in the DC datastream. It is always a good idea to have a <dc:title> element in a Fedora DC datastream.

I think, in the end, we will have to replace the built-in XML form with one of own own, which isn't the end of the world. Just thought I'd bring up these issues that came up during my testing.

**Comment by patdunlavey** [comment]
I don't see an obvious problem here, nor an obvious solution. So I'm going to mark it as won't fix.
