### ISSUE TITLE
Double Confirmation messages

### ISSUE THREAD

**Issue by petermacdonald** [commonmedia/islandora_webform#5]
I'm running into a problem with IW that seems to be related to the AJAX options in "Form Settings" for the webform.

1. If I placed a check in "Inline AJAX mode" - the "Submit" button on the webform doesn't work and I don't see any confirmation message, and I get the following in the watchdog logs.

	Warning: array_unshift() expects parameter 1 to be array, null given in ajax_render() (line 295 of /home/lisham/public_html/includes/ajax.inc).
	Warning: array_merge(): Argument #2 is not an array in ajax_render() (line 288 of /home/lisham/public_html/includes/ajax.inc).	
	Warning: array_merge(): Argument #2 is not an array in ajax_form_callback() (line 404 of /home/lisham/public_html/includes/ajax.inc).
	Notice: Undefined index: #commands in ajax_form_callback() (line 404 of /home/lisham/public_html/includes/ajax.inc).

2. If I place a check in both "Inline AJAX mode" and "Show confirmation screen" - The confirmation message displays twice.

2 is the better of these options, but I see double Confirmation messages, which I don't think I should.

**Comment by patdunlavey** [comment]
Since this is not an issue with the islandora_webform module, I'm closing and marking as "won't fix".
