### ISSUE TITLE
webform with DOI - no journal title

### ISSUE THREAD

**Issue by ws155west** [commonmedia/islandora_webform#51]
I'm using the DOI feature, and when it pulls in metadata, there is no journal title (host:title) field or value. Abstract is missing, too.
![image](https://user-images.githubusercontent.com/25694647/72621495-5c0efc00-390f-11ea-861a-0ebda9f63f4f.png)

**Comment by noahwsmith** [comment]
@ws155west we'll take a look- thanks for logging this issue! cc @sarah-lippincott

**Comment by noahwsmith** [comment]
@ws155west this should be all set - have your IT folks pull the latest in the `7.x` branch and this issue should be solved. You may need to clear caches to get the new code in place. Let me know if you have trouble with it and I can try to help - we had to elbow Drupal hard to get our demo server to use the revised code. See #53 for a screenshot of how it should look ("Host: title" should be blue after the update)
